import type { Metadata } from "next";
import { Geist, Geist_Mono, Inter, Protest_Riot, Hi_Melody } from "next/font/google";
import "./globals.css";

const inter = Inter({
  subsets: ['latin'],
  weight: ['400', '700'],
  variable: '--font-inter',
  display: 'swap',
});

const protestRiot = Protest_Riot({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-protest',
  display: 'swap',
});
const himelody = Hi_Melody({
  subsets: ['latin'],
  weight: ['400'],
  variable: '--font-melody',
  display: 'swap',
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${inter.variable} ${protestRiot.variable} antialiased`}
      >

        {children}
      </body>
    </html>
  );
}
